global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
  minecraft:
    address: ":25565"
  minecraft-rl:
    address: ":25566"

providers:
 file:
    filename: /config.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: "tomek.skrond@gmail.com"  # Replace with your email address
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
log:
  level: DEBUG
